# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://newtestdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a3b665cb7ce34a5eba8b44ec458f294c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9a1f8f4340ab41ef9933e6f7bb7f66e2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: newtestdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a3b665cb7ce34a5eba8b44ec458f294c }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a36a37e52a043b9ae99268d17f9c938 }}
        images: 'newtestdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a3b665cb7ce34a5eba8b44ec458f294c }}/studentperformance:${{ github.sha }}'